Issue #514: Add `--single-plugin` option to mount a single plugin
This patch adds a new (opt-in) parameter to mount a single plugin at a time on KTD.
This way you can be confident there's no interference from other plugins, specially when running DB-dependent tests.

To test:
1. Have some dir with some cloned plugins. e.g.:
   $ mkdir -p ~/git/koha-plugins
   $ cd ~/git/koha-plugins
   $ git clone https://github.com/thekesolutions/koha-plugin-innreach-ill.git innreach-ill
   $ git clone https://github.com/bywatersolutions/dev-koha-plugin-kitchen-sink.git kitchen-sink
2. Run with `--plugins` only:
   $ ktd --proxy --name plugins \
         --plugins up -d \
         && ktd --name plugins --logs
=> SUCCESS: It loads, you see INN-Reach and Kitchen-sink get enabled. It finishes
3. Shut it:
   $ ktd --name plugins down
4. Apply this patch
5. Repeat 2
=> SUCCESS: Same thing! No behavior change
6. Repeat 3
7. Run:
   $ ktd --proxy --name plugins --plugins \
       --single-plugin ~/git/koha-plugins/kitchen-sink
       up -d && ktd --name plugins --logs
=> SUCCESS: It fails! Cannot do both!
8. Run:
   $ ktd --proxy --name plugins \
       --single-plugin ~/git/koha-plugins/kitchen-sink
       up -d && ktd --name plugins --logs
=> SUCCESS: Same as 2, but only Kitchen-sink loads
9. Sign off :-D

Bonus: You should also check on each of these that only the expected plugin is mounted:
   $ ktd --name --plugins --shell
  k$ ls -l /kohadevbox/plugins
=> SUCCESS: Shows what you requested (all, a single one, etc)

Signed-off-by: Tomás Cohen Arazi <tomascohen@theke.io>

diff --git a/bin/ktd b/bin/ktd
--- a/bin/ktd
+++ b/bin/ktd
@@ -45,6 +45,7 @@ Options:
     --os1                 Use an OpenSearch 1.x container
     --os2                 Use an OpenSearch 2.x container
     --plugins             Enable plugin development environment
+    --single-plugin PATH  Mount a single plugin from PATH to /kohadevbox/plugins/
     --selenium            Use a Selenium container
     --sso                 Use a Keycloak container
     --shell               Get into the Koha container
@@ -184,6 +185,15 @@ set_image()
     fi
 }
 
+toggle_plugins()
+{
+    if [ "$SINGLE_PLUGIN_PATH" != "" ] && [ "$ENABLE_PLUGINS" != "no" ]; then
+        printf "\nError: --plugins and --single-plugin are mutually exclusive\n\n"
+        usage
+        exit 1
+    fi
+}
+
 ENV_DB_IMAGE=$DB_IMAGE
 ENV_ES_IMAGE=$ES_IMAGE
 ENV_KOHA_IMAGE=$KOHA_IMAGE
@@ -205,6 +215,7 @@ WAIT_READY="no"
 ENABLED_SEARCHENGINE=""
 
 ENABLE_PLUGINS="no"
+SINGLE_PLUGIN_PATH=""
 ENABLE_SELENIUM="no"
 ENABLE_SSO="no"
 ENABLE_LOCAL_RUN_SCRIPT="no"
@@ -260,7 +271,12 @@ while [ $# -gt 0 ]; do
             shift ;;
         --plugins)
             ENABLE_PLUGINS="yes"
+            toggle_plugins
             shift ;;
+        --single-plugin)
+            SINGLE_PLUGIN_PATH="$2"
+            toggle_plugins
+            shift 2 ;;
         --proxy)
             USE_PROXY="yes"
             shift ;;
@@ -438,6 +454,16 @@ else
 
             if [ "$ENABLE_PLUGINS" != "no" ]; then
                 COMPOSE_OPTIONS="${COMPOSE_OPTIONS} -f compose/plugins.yml"
+            fi
+
+            if [ "$SINGLE_PLUGIN_PATH" != "" ]; then
+                if [ ! -d "$SINGLE_PLUGIN_PATH" ]; then
+                    printf "\nError: Single plugin path '$SINGLE_PLUGIN_PATH' does not exist or is not a directory\n\n"
+                    exit 1
+                fi
+                export SINGLE_PLUGIN_PATH="$SINGLE_PLUGIN_PATH"
+                export SINGLE_PLUGIN_NAME="$(basename "$SINGLE_PLUGIN_PATH")"
+                COMPOSE_OPTIONS="${COMPOSE_OPTIONS} -f compose/single_plugin.yml"
             fi
 
             if [ "$ENABLE_SELENIUM" != "no" ]; then
